Fix state update that might cause race condition
reactjs/reactjs.org pull request #3245
Opened 2020-09-06 20:33 UTC by ugultopu

In React, state updates might be asynchronous. Hence, when updating state based on old state or props, `setState` should receive a function as its argument instead of an object.

More information: https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous

2020-09-07 06:21 UTC, eps1lon requested changes
This is an introductory section that is about equivalence to the hooks example above. It was likely deliberate to not use functional state updates at this point.

2020-09-07 06:35 UTC, ugultopu reviewed
Regardless, it should not encourage bad practices. Either the recommendation about using function parameter version `setState` when previous state is being referred should be changed, or this example needs to be fixed.

2020-09-07 10:11 UTC, crypt096 approved these changes

2020-12-09 13:54 UTC, ugultopu commented
Can this either be rejected or be merged?

2021-05-11 07:04 UTC, eps1lon commented
This should be adressed by https://github.com/reactjs/reactjs.org/issues/3308

2021-05-12 08:01 UTC, eps1lon commented
It's just that this is an introductory section so we need to be careful with the amount of React API we expose. But at the same time the example is problematic. 

The question is if we want to experiment with the introductory section when there's already work going on.

2021-07-06 18:08 UTC, closed without merging