Add PropType instructions for functional components
reactjs/reactjs.org pull request #3403
Opened 2020-11-23 23:34 UTC by renatodex

## What changed?
I've added a new block of instructions for people using React with Functional components.

## Why did you do it?
It may not be super obvious how to apply the PropTypes to functional components, so I thought it would be a good way.

## Note
Also, this is my first contribution to React, so please tell me If I missed something!

2020-11-23 23:38 UTC, renatodex commented
Oh, I signed the CLA, do I need to take any other action, or the `Facebook CLA Check` will trigger again automatically?

2020-11-24 09:25 UTC, eps1lon requested changes
Much appreciated, thanks! Needs some editorial work though.

2020-11-24 09:25 UTC, eps1lon commented on content/docs/typechecking-with-proptypes.md
> +### Functional Components
```suggestion
### Function Components
```

2020-11-24 09:25 UTC, eps1lon commented on content/docs/typechecking-with-proptypes.md
> +If you are using Functional Components in your regular development, you may want to make some small changes to allow PropTypes to be proper applied.
```suggestion
If you are using function components in your regular development, you may want to make some small changes to allow PropTypes to be proper applied.
```

"function components" isn't treated as a proper noun in the docs as far as I can tell.

2020-11-24 09:25 UTC, eps1lon commented on content/docs/typechecking-with-proptypes.md
> +Let's say you have a simple component like this:
```suggestion
Let's say you have a component like this:
```
What is simple to you may not be simple to others.

2020-11-24 09:25 UTC, eps1lon commented on content/docs/typechecking-with-proptypes.md
> +export default function ({ name }) {
Could you give this a name? React is discouraging anonymous functions since they appear as "unknown" in component stack traces.

2020-11-24 09:25 UTC, eps1lon commented on content/docs/typechecking-with-proptypes.md
> +To add PropTypes, you may want to isolate component in a constant before exporting, like this:
```suggestion
To add PropTypes, you may want to isolate the component in a constant before exporting, like this:
```

2020-11-24 09:25 UTC, eps1lon commented on content/docs/typechecking-with-proptypes.md
> +const HelloWorldComponent = function ({ name }) {
```suggestion
function HelloWorldComponent({ name }) {
```
Same as above regarding named functions.

2020-11-24 09:25 UTC, eps1lon commented on content/docs/typechecking-with-proptypes.md
> +Then, adding PropTypes should be easy:
```suggestion
Then, you can add PropTypes directly to the `HelloWorldComponent`:
```

Same as above regarding "simple".

2020-11-24 09:25 UTC, eps1lon commented on content/docs/typechecking-with-proptypes.md
> +const HelloWorldComponent = function ({ name }) {
```suggestion
function HelloWorldComponent({ name }) {
```

2020-11-24 19:58 UTC, renatodex commented
@eps1lon comments addressed !

2020-11-25 09:18 UTC, eps1lon approved these changes

2020-11-25 09:20 UTC, merged