remove componentWillMount/WillReceiveProps
reactjs/reactjs.org pull request #3475
Opened 2021-01-04 21:27 UTC by amen-souissi

componentWillMount and componentWillReceiveProps are no longer supported by React

2021-01-05 08:56 UTC, eps1lon requested changes
That's a good point.

They're still supported though with an `UNSAFE_` prefix. I think they should be mentioned so that people don't wonder when these methods are called.

Maybe like https://reactjs.org/docs/react-component.html#mounting does?

2021-01-06 13:49 UTC, amen-souissi commented
Maybe something like this ?


When a component updates, the instance stays the same, so that state is maintained across renders. React updates the props of the underlying component instance to match the new element, and calls `UNSAFE_componentWillReceiveProps()`, `UNSAFE_componentWillUpdate()` and `componentDidUpdate()` on the underlying instance.

Next, the `render()` method is called and the diff algorithm recurses on the previous result and the new result.

>Note:
>
>These methods are considered legacy and you should [avoid them](/blog/2018/03/27/update-on-async-rendering.html) in new code:
>
>- `UNSAFE_componentWillUpdate()`
>- `UNSAFE_componentWillReceiveProps()`

2021-01-06 14:51 UTC, eps1lon commented
Seems good to me :+1:

2021-01-06 19:30 UTC, eps1lon approved these changes

2021-01-06 19:43 UTC, eps1lon commented
Thanks!

2021-01-06 19:43 UTC, merged