fix(sandpack): improve memory usage
reactjs/reactjs.org pull request #4126
Opened 2021-11-26 08:23 UTC by danilowoz

2022-01-24 20:47 UTC, gaearon commented
can you rebase this please?

2022-01-25 18:22 UTC, gaearon commented
This seems like a nice improvement but pretty flaky.

If I scroll up and down a lot, I'm able to trigger a situation where the in-viewport sandbox has no preview.

<img width="1161" alt="Screenshot 2022-01-25 at 18 21 12" src="https://user-images.githubusercontent.com/810438/151035977-e6ab65b1-ae98-44f0-a123-772ebdd42905.png">

2022-01-25 18:23 UTC, gaearon requested changes
need to improve the viewport detection because it's not reliable.

2022-01-28 09:50 UTC, danilowoz commented
@gaearon It got stuck in an intermediate step between unmounting and remounting the client, and it needed a couple of tweaks on Sandpack side and yours in order to make it work correctly. But from now on, no matter how insanely you scroll, it always mounts the preview again.

Unfortunately, it still takes some time to load the sandbox dependencies once again between this transition (that isn't the nicest experience for the user). But as I mentioned before, we've been working in an internal refactor to skip the transpile step, which will likely improve the dependencies loading a lot.

2022-01-28 19:05 UTC, gaearon commented
this seems exceedingly aggressive to me — notice sometimes it seems to clean up something that's _already rendered_, only to render it again. what do you think about increasing the distance that's necessary for a sandbox to be unloaded? and ideally it would never destroy something that hasn't been destroyed anyway and is already in view again.

https://user-images.githubusercontent.com/810438/151606203-4a44b77a-fefb-469d-a513-38257a2330e3.mov

2022-02-01 16:52 UTC, gaearon commented
i think i see a bug.

1) scroll to any sandbox
2) scroll far down
3) scroll back up
4) introduce a syntax error

expected: the output shows a compile error message
actual: we see the last rendered output

2022-02-02 11:11 UTC, danilowoz commented
@gaearon fixed!

2022-02-02 11:38 UTC, gaearon commented
let's give this a go!

2022-02-02 11:40 UTC, gaearon commented
stray log?

<img width="234" alt="Screenshot 2022-02-02 at 11 40 16" src="https://user-images.githubusercontent.com/810438/152146981-8af2a4d4-615b-4b3a-9043-55f02a7a7483.png">

2022-02-02 11:44 UTC, gaearon commented
(it's not a blocker though, let's get this in)

2022-02-02 11:44 UTC, merged