fix(sandpack): make sure iframe has always the same height and position
reactjs/reactjs.org pull request #4288
Opened 2022-02-04 09:39 UTC by danilowoz

In order to avoid layouts shift (especially on mobile devices), I added a set o measures:
- Adds a new state to make sure the current Sandpack has the latest updated height from the iframe protocol (on unmount it's out to date);
- Removes the absolute position, which was the main reason for the shift (why was it necessary?);

2022-02-04 11:05 UTC, harish-sethuraman commented
What if the output turns out to be smaller than the reserved area? 
Seems like the output window is resized (height decreases) and the content below that moves up.

2022-02-08 15:59 UTC, danilowoz commented
Hey, @harish-sethuraman I'm not sure I got about the problem. Could you make a screen recording? 
I shouldn't cause any problems related to the height, as the purpose of my changes is to make the loading state more reliable and avoid the preview going away off the container (causing a resizing).

2022-02-08 16:08 UTC, gaearon commented
The absolute position is for this:

https://user-images.githubusercontent.com/810438/153027467-e44cd8dd-6f2c-4de9-a656-43dc0a8d9bac.mov

2022-02-08 16:08 UTC, gaearon requested changes
error screen jumps down

2022-02-08 16:11 UTC, harish-sethuraman commented
https://user-images.githubusercontent.com/32865581/153028025-e9e10806-e6db-4962-abe1-da0fffe14bd9.mov

These outputs are smaller than the initial width? and height reduces?

2022-02-12 02:11 UTC, gaearon commented
>These outputs are smaller than the initial width? and height reduces?

At least that shouldn't be an issue on main after #4322.

2022-02-15 11:06 UTC, danilowoz commented
I'm going to close this, as the layout shift has been fixed in another PR

2022-02-15 11:06 UTC, closed without merging