added code for sandpack console
reactjs/reactjs.org pull request #4672
Opened 2022-05-22 16:11 UTC by harish-sethuraman

Code is something similar to https://github.com/codesandbox/sandpack/pull/301

2022-05-22 17:51 UTC, harish-sethuraman commented
@danilowoz Seems like the new bundler doesn't emit `console` type messages. But the old one does emit so I've reverted that in this PR.

2022-05-22 18:48 UTC, harish-sethuraman commented on beta/src/components/MDX/Sandpack/SandpackRoot.tsx
> +    showConsole = true,
We can disable this when we are done testing

2022-05-23 16:48 UTC, danilowoz commented
Hey @harish-sethuraman, I noted that after a few consoles, the list is overlapping the preview: 

<img width="978" alt="Screenshot 2022-05-23 at 17 42 23" src="https://user-images.githubusercontent.com/4838076/169868859-052a222b-8131-491c-bfa1-c5a8a6284e70.png">

2022-05-24 08:32 UTC, danilowoz commented
Hey @harish-sethuraman, the following sandbox is breaking the whole page. I think there is something wrong with the render of each console message
<img width="964" alt="Screenshot 2022-05-24 at 09 29 57" src="https://user-images.githubusercontent.com/4838076/169986661-09af50c4-c93b-42f8-a61b-2cf10fb6a2ef.png">

2022-05-24 18:13 UTC, gaearon requested changes
It's a good start. 

- Let's limit this to `console.log` only. No errors or warnings.
- JSON.stringify call needs to be in try/catch. If it fails, try `Object.prototype.toString.call(value)`. If that throws too, just print `"[" + typeof(value) + "]"`.
- Remove the "no action" cursor over the console bar, it's confusing IMO.
- Change "console" to "Console". Align text to the left.
- Add a bit more padding. Use the same horizontal padding as in the top bar. Basically, on mobile, try to make "Console" label align with "Show more" label, and make arrows the same size/position.
- When you print objects like `console.log("hi", {}, {})` the vertical space between objects is too large. Put them closer. The excessive indentation is also strange, let's remove it.
- When the console is empty, expanding it should still work. It should just expand some area with a min height of one line. So that you know this is where console messages will appear.
- The sandbox loading indicator should not overlap the console. Position it so that it is above it (when the console is present)?
- When there's an error, console logs should not disappear or change their count.
- Sometimes putting a `console.log` into component body and then edit it causes to console to always clear before next render. I don't know why. Seems like a bug.

2022-05-25 04:31 UTC, harish-sethuraman commented
> When there's an error, console logs should not disappear or change their count.

When there is a sandpack error there were two consoles emmited. One is `Error in the sandbox` message which is of type `log` and another `error`. How can we go about blocking this `Error in the sandbox` message?

2022-05-25 04:44 UTC, harish-sethuraman commented
> Hey @harish-sethuraman, the following sandbox is breaking the whole page. I think there is something wrong with the render of each console message

Seems to be because the event's object cannot be mapped? Ill have a look into it :)

2022-05-25 13:15 UTC, gaearon commented
The error with event object is likely that it can’t be JSON.stringify’ed because it’s circular. This is why I suggested a try/catch.

2022-05-31 16:18 UTC, gaearon commented
@harish-sethuraman Do you expect to be able to finish it this week?

2022-05-31 16:22 UTC, harish-sethuraman commented
Will try to wrap up kinda caught up with other works.

2022-05-31 17:01 UTC, harish-sethuraman commented
@gaearon  Can you check now? Also I'm wondering if this works in local for you? I'm getting CORS error

2022-05-31 17:23 UTC, harish-sethuraman commented
- When you print objects like console.log("hi", {}, {}) the vertical space between objects is too large. Put them closer. The excessive indentation is also strange, let's remove it.

This is because the message `{}` is not considered to be string and it is rendered inside `SandpackCodeViewer`. We can reduce the vertical space but the same will apply for other objects too? 

How it looks 
![Screenshot 2022-05-31 at 10 48 07 PM](https://user-images.githubusercontent.com/32865581/171234674-af0a04a7-ff11-455a-b920-53364fa21d40.png)

How it will look
![Screenshot 2022-05-31 at 10 48 30 PM](https://user-images.githubusercontent.com/32865581/171234857-c3244b57-dee7-461a-9bae-4e5dbf4cfde3.png)

-  The sandbox loading indicator should not overlap the console. Position it so that it is above it (when the console is present)?

This one is not reproducible for me? The console appears only after the sandbox loader has gone away? 

- When there's an error, console logs should not disappear or change their count. Sometimes putting a console.log into component body and then edit it causes to console to always clear before next render. I don't know why. Seems like a bug.

This is because we are listening to the `start` message from Sandpack. I use start because when we move away from sandpack it is killed (I dont see any event specific to sandpack getting killed) then when we scroll up again the consoles appear again. @danilowoz  which event is recommended for clearing console?

2022-06-03 17:59 UTC, gaearon commented
>How it will look

seems fine to me

>This one is not reproducible for me? The console appears only after the sandbox loader has gone away?

hmm i don't remember how i got this. ok let's ignore for now

2022-06-03 18:01 UTC, gaearon commented
@lebo any thoughts on the console design? can we keep it like this or need to redo it? add `console.log('foo')` to any sandbox on https://beta-reactjs-b2bt5iob0-fbopensource.vercel.app/learn to try it. we'd hide it until first message by default so it'll only show up when you use console

2022-06-03 18:43 UTC, lebo commented
Looks cool! UX seems right (having it as a collapsible section that appears once there's something logged). 

Design wise, I think it could match the code section a bit more. Any opposition to using the monospace font and aligning the margins, line height, and spacing? Also we should probably remove the 2px border and just do a bottom border on all items except for :last.

2022-06-10 18:28 UTC, gaearon commented
We need to keep the normal font for the "Console" header itself. Monospace is just for the content.

2022-06-10 18:29 UTC, gaearon commented
And let's make the console hidden until the first `console.log` statement runs.

2022-06-10 19:00 UTC, gaearon commented on beta/src/components/MDX/Sandpack/CustomPreset.tsx
> +            <div className="sp-stack h-full">
This breaks the narrow view.

<img width="970" alt="Screenshot 2022-06-10 at 20 00 32" src="https://user-images.githubusercontent.com/810438/173132719-9360e276-fb14-4df4-9998-187ad789cacf.png">

2022-06-10 19:35 UTC, merged