feat: hide social banner on scroll
reactjs/reactjs.org pull request #4792
Opened 2022-07-05 09:15 UTC by akulsr0

This hides social banner when scrolled on mobile/tablet.

**Demo**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43666833/177294292-ab72b973-05bd-4797-9e4b-5c4d0a0ce35a.gif)

2022-07-07 17:42 UTC, akulsr0 commented
@harish-sethuraman @gaearon any feedback/suggestions here?

2022-07-07 18:19 UTC, harish-sethuraman commented
Hey 👋🏻  There is one another PR that fixes the same thing 
- https://github.com/reactjs/reactjs.org/pull/4713

2022-07-09 11:21 UTC, akulsr0 commented
@harish-sethuraman Yeah, I see there were some changes requested and that pr was not active ~1 month, so I tried a different approach here to fix the issue.
Since on smaller devices, the social banner is taking much space, it would be good to fix this with either approach :)

2022-07-25 13:53 UTC, akulsr0 commented
Bump?

2022-07-25 17:24 UTC, gaearon commented on beta/src/components/Layout/Sidebar/Sidebar.tsx
> +    const scrollAmount = document.documentElement.scrollTop;
We shouldn't be reading global mutable values during render. This usually indicates a bug (even when it's not obvious how to trigger it).

2022-07-25 17:27 UTC, gaearon commented on beta/src/components/Layout/Sidebar/Sidebar.tsx
> +  if (typeof window !== 'undefined') {
Different render outputs for server and initial client output means hydration can produce mismatches. This doesn't seem right.

2022-07-25 17:28 UTC, gaearon requested changes
From the coding perspective, this solution doesn't seem to follow React's rules. There should be the same render output for server and initial client, and render shouldn't read mutable values. So I don't think we can merge this.

2022-09-07 03:20 UTC, closed without merging