fix: reset showHint to false when click Next Challenge
reactjs/reactjs.org pull request #4948
Opened 2022-08-30 06:42 UTC by CassieRan

resolve [#4947](https://github.com/reactjs/reactjs.org/issues/4947)

2022-08-30 15:12 UTC, gaearon requested changes
can we split this into two components?

the outer component tracks the current ID.

the inner component contains state local to a single challenge — like whether to show hint, and whether to show the solution.

the outer component passes `key={id}` to the inner component, resetting its state on ID change.

2022-08-31 02:26 UTC, CassieRan commented
@gaearon Sure, you inspired me a lot, I'll get a try.

2022-08-31 03:23 UTC, CassieRan commented on beta/src/components/MDX/Challenges/Challenges.tsx
> +  }, [activeChallenge]);
The legency logic doesn't work, I'm not sure that it's caused by the `activeChallenge` state leads to re-render, then put these logic in Effect.

2022-08-31 03:26 UTC, CassieRan commented
@gaearon Updated, could you take a look when you're available?

2022-09-01 06:35 UTC, harish-sethuraman commented on beta/src/components/MDX/Challenges/Challenges.tsx
> +          }></Challenge>
```suggestion
        <Challenge
          key={activeChallenge}
          isRecipes={isRecipes}
          currentChallenge={currentChallenge}
          totalChallenges={totalChallenges}
          hasNextChallenge={!!nextChallenge}
          handleClickNextChallenge={() =>
            handleChallengeChange(nextChallenge?.id)
          } />
```

2022-09-01 06:35 UTC, harish-sethuraman commented on beta/src/components/MDX/Challenges/Challenge.tsx
> +        <>{currentChallenge.content}</>
Do we really need a Fragment here?

2022-09-01 07:47 UTC, CassieRan commented on beta/src/components/MDX/Challenges/Challenge.tsx
> +        <>{currentChallenge.content}</>
Absolutely not, I've removed it.

2022-09-01 07:49 UTC, CassieRan commented on beta/src/components/MDX/Challenges/Challenges.tsx
> +    React.useState(false);
Add `activeChallengeHasChanged` to flag whether the activeChallenge has changed to avoid scrolling to Challenges when page mounted.

2022-09-01 07:51 UTC, CassieRan commented
@harish-sethuraman Updated

2022-09-03 17:26 UTC, gaearon commented
Thanks. I simplified the logic a bit.

2022-09-03 17:26 UTC, merged