Display ctrl key in search bar for non-mac browsers
reactjs/reactjs.org pull request #5202
Opened 2022-10-23 14:23 UTC by jirkavrba

In the new documentation, there is an option key displayed for all users in the search bar.
This PR provides a check for the navigator platform and changes the displayed key to `Ctrl` when displayed on Windows or Linux.

**Search bar displayed on Mac**
![image](https://user-images.githubusercontent.com/14146321/197397395-b2c9bc22-d87f-474e-95fa-5da984c4f6db.png)

**Search bar displayed on Windows/Linux**
![image](https://user-images.githubusercontent.com/14146321/197397403-b8e07cd3-e904-4946-a0e2-882b8d404b51.png)

2022-10-24 02:38 UTC, arafatiqbal commented
I like this, nice!

2022-11-14 23:54 UTC, gaearon requested changes
This doesn't work for initially rendered HTML. Can you instead make it so that we know the platform in advance? E.g. by detecting it in an inline script that runs before the rest of the page, and setting an appropriate HTML class name on the document.

2022-11-16 09:19 UTC, jirkavrba commented
I've added the platform detection via an inline script, but I had some troubles with integrating it within the component (as `document` is not available during the initial render)

Can anybody please point me at how that reading from document could be accomplished during the initial render?

2022-11-16 09:25 UTC, jirkavrba commented
Thanks a lot, I'll implement it this way

2023-03-18 17:19 UTC, jirkavrba commented
Because the search bar component has changed quite a lot since I opened this PR I will close it and I will open a new PR with changes to the current version.

The original issue that this PR is trying to solve seems to be still present on the website.

2023-03-18 17:19 UTC, closed without merging